name: CRUD-DD-TASK-MEAN-APP

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-image:latest ./backend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-image:latest

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-image:latest ./frontend

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-image:latest


  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: ${{ secrets.EC2_PROJECT_PATH }}
          overwrite: true


      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_PROJECT_PATH }}

            echo "Pulling latest images from Docker Hub..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend-image:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-image:latest

            echo "Rebuilding and restarting containers..."
            docker compose down
            docker compose up --build -d

            echo "Deployment completed!"
